repos:
    - repo: local
      hooks:
          - id: run-pre-commit-script
            name: Run Pre-Commit Script
            entry: ./.pre-commit-script.sh
            language: system
            require_serial: true
            types: [text]
            verbose: false