repos:
    - repo: local
      hooks:
          - id: run-pre-commit-script
            name: Run Pre-Commit Script
            entry: ./.pre-commit-script.sh
            language: system
            types: [text]