name: 👨‍🎨 Code Quality

on:
    pull_request:
    workflow_dispatch:

concurrency:
    group: run-lint-${{ github.event.number }}
    cancel-in-progress: true

jobs:
    lint:
        name: "🧑‍✈️ Run Lint"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write

        steps:
            # checkout your repository
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🐍 Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.13'

            -   name: 🧑‍✈️ Run lint check
                run: |
                    python3 -m venv .venv
                    source .venv/bin/activate
                    pip install -r requirements.txt
                    gdlint .

    format:
        name: "🕵️ Run Format"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write
        steps:
            # checkout your repository
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🐍 Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.13'

            -   name: 🕵️ Run format check
                run: |
                    python3 -m venv .venv
                    source .venv/bin/activate
                    pip install -r requirements.txt
                    gdformat .
