name: 👨‍🎨 Code Quality

on:
    pull_request:
    workflow_dispatch:

concurrency:
    group: run-lint-${{ github.event.number }}
    cancel-in-progress: true

jobs:
    lint:
        name: "🧑‍✈️ Run Lint"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write

        steps:
            # checkout your repository
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🌱 Setup Python and venv
                uses: ./.github/actions/setup-venv

            -   name: 🧑‍✈️ Run lint check
                run: gdlint .

    format:
        name: "🕵️ Run Format"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write
        steps:
            # checkout your repository
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🌱 Setup Python and venv
                uses: ./.github/actions/setup-venv

            -   name: 🧑‍✈️ Run format check
                run: gdformat .

    architecture:
        name: "🏗️ Check Architecture"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write
        steps:
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🏗️ Run architectural constraints check
                shell: bash
                run: |
                    chmod +x ./scripts/strict-layers.sh
                    ./scripts/strict-layers.sh --directory src

    blueprints:
        name: "🎨 Check Item Blueprints"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write
        steps:
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: 🎨 Run blueprint verification
                shell: bash
                run: |
                    chmod +x ./scripts/verify-item-blueprints.sh
                    ./scripts/verify-item-blueprints.sh
