name: Run tests

run-name: ${{ github.head_ref || github.ref_name }}-run-tests

on:
    pull_request:
        paths-ignore:
            - '**.yml'
            - '**.md'
    workflow_dispatch:


concurrency:
    group: run-tests-${{ github.event.number }}
    cancel-in-progress: true


jobs:
    unit-test:
        name: "Run Unit Tests"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write

        steps:
            # checkout your repository
            -   uses: actions/checkout@v4
                with:
                    lfs: true

            # run tests by using the gdUnit4-action with Godot version 4.2.1 and the latest GdUnit4 release
            -   uses: MikeSchulze/gdUnit4-action@v1.1.1
                with:
                    godot-version: '4.3'
                    paths: |
                        res://tests/
                    timeout: 5
                    report-name: tests_report.xml



            # download the artifact
            -   name: Download test report artifact
                uses: actions/download-artifact@v4
                with:
                    name: artifact_tests_report.xml
                    path: ./reports

            -   name: List files
                run: |
                    ls .
                    echo ----------------
                    ls ./reports/
                    echo ----------------
                    ls ./reports/report_1
                    echo ----------------
                    ls ./reports/report_1/css
                    echo ----------------
                    ls ./reports/report_1/path
                    echo ----------------
                    ls ./reports/report_1/test_suites
                    echo ----------------
                    

            # unzip the artifact
            -   name: Unzip test report artifact
                run: unzip ./reports/report_1//artifact_tests_report.xml.zip -d ./reports

                # deploy to GitHub Pages
            -   name: Deploy to GitHub Pages
                run: |
                    git config --global user.name 'github-actions'
                    git config --global user.email 'github-actions@github.com'
                    git checkout -b gh-pages
                    cp -r ./test-report/* .
                    git add .
                    git commit -m 'Deploy test report to GitHub Pages'
                    git push --force --set-upstream origin gh-pages