name: 🧑‍🔬 Run tests

run-name: ${{ github.head_ref || github.ref_name }}-run-tests

on:
    pull_request:
    workflow_dispatch:


concurrency:
    group: run-tests-${{ github.event.number }}
    cancel-in-progress: true


jobs:
    unit-test:
        name: "🧪 Run Unit Tests"
        runs-on: 'ubuntu-22.04'
        timeout-minutes: 10 # The overall timeout
        permissions:
            actions: write
            checks: write
            contents: write
            pull-requests: write
            statuses: write

        steps:
            # checkout your repository
            -   name: 📥 Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true

            # Documentation: https://github.com/marketplace/actions/setup-godot-action
            -   name: 🤖 Setup Godot
                uses: chickensoft-games/setup-godot@v1
                with:
                    # Version must include major, minor, and patch, and be >= 4.0.0
                    # Pre-release label is optional.
                    version: 4.3.0 # also valid: 4.0.0.rc1 or 4.0.0, etc
                    # Use .NET-enabled version of Godot (the default is true).
                    use-dotnet: false
                    # Include the Godot Export Templates (the default is false).
                    include-templates: false

            -   name: 🔬 Verify Setup
                run: |
                    godot --version
                    echo $PWD
                    ls -la

            -   name: 🧪 Run Tests
                run : |
                    godot --headless --import
                    godot --headless --path "$PWD" -s addons/gut/gut_cmdln.gd 

            -   name: 📝 Tests Summary
                uses: test-summary/action@v2
                with:
                    paths: ".test_results.xml"
                    output: test-summary.md
                if: always()


            -   name: 📤 Upload Test Summary
                uses: actions/upload-artifact@v4
                with:
                    name: test-summary
                    path: test-summary.md
                if: always()


            - name: 🔎 Find Comment
              uses: peter-evans/find-comment@v3
              id: fc
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: '<img src="https://svg.test-summary.com/dashboard.svg?'
              if: always()

            - name: ✏️ Create or update comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body-path: 'test-summary.md'
                  edit-mode: replace
              if: always()
